kuka_youbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Effort controllers -----------------------------------
  arm_joint_1_Effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_joint_1
 
  arm_joint_2_Effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_joint_2

  arm_joint_3_Effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_joint_3
 
  arm_joint_4_Effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_joint_4

  arm_joint_5_Effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_joint_5

  gripper_finger_joint_l_Effort_controller:
    type: effort_controllers/JointEffortController
    joint: gripper_finger_joint_l

  gripper_finger_joint_r_Effort_controller:
    type: effort_controllers/JointEffortController
    joint: gripper_finger_joint_r


  # Position controllers -----------------------------------
  arm_joint_1_Position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_1

  arm_joint_2_Position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_2

  arm_joint_3_Position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_3

  arm_joint_4_Position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_4

  arm_joint_5_Position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_5

  gripper_finger_joint_l_Position_controller:
    type: position_controllers/JointPositionController
    joint: gripper_finger_joint_l

  gripper_finger_joint_r_Position_controller:
    type: position_controllers/JointPositionController
    joint: gripper_finger_joint_r

    
  # Velocity controllers -----------------------------------

  arm_joint_1_Velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_joint_1

  arm_joint_2_Velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_joint_2

  arm_joint_3_Velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_joint_3

  arm_joint_4_Velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_joint_4

  arm_joint_5_Velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_joint_5

  gripper_finger_joint_l_Velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: gripper_finger_joint_l

  gripper_finger_joint_r_Velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: gripper_finger_joint_r
