controller_joint_names: 
['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5',
'caster_joint_fl','caster_joint_fr','caster_joint_bl','caster_joint_br',
'wheel_joint_fl','wheel_joint_fr','wheel_joint_bl','wheel_joint_br',
 ]